# Parker McQuade
# Week 11 - March 30th, 2023
# Python Numpy - Processing Arrays 

In [1]:
import numpy as np

In [2]:
lst = [11,22,33,44,55,66,77]
lst

[11, 22, 33, 44, 55, 66, 77]

In [4]:
arr_1d = np.array(lst)
arr_1d

array([11, 22, 33, 44, 55, 66, 77])

In [5]:
arr_1d.dtype

dtype('int32')

In [8]:
lst1 = [1,2,3,4,5]
lst2 = [11,12,13,14,15]
lst = [lst1,lst2]
lst


[[1, 2, 3, 4, 5], [11, 12, 13, 14, 15]]

In [9]:
arr_2d = np.array(lst)
arr_2d

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [10]:
arr_2d.ndim

2

In [11]:
arr_2d.shape

(2, 5)

In [12]:
arr_2d.dtype

dtype('int32')

In [13]:
fruits = ['Orange', 'Apple', 'Cherry', 'Grape']
arr_1d = np.array(fruits)
arr_1d

array(['Orange', 'Apple', 'Cherry', 'Grape'], dtype='<U6')

In [14]:
arr_1d.dtype

dtype('<U6')

In [15]:
arr_1d = np.array(['Orange', 'Apple', 'Cherry', 'Grape', 1,2,3,4,5,True,False,[1,2,3,4]])

In [16]:
arr_1d

array(['Orange', 'Apple', 'Cherry', 'Grape', 1, 2, 3, 4, 5, True, False,
       list([1, 2, 3, 4])], dtype=object)

In [17]:
arr_1d.dtype

dtype('O')

In [21]:
arr_1d = np.array([11,12,13,14,15],dtype='i8')
arr_1d

array([11, 12, 13, 14, 15], dtype=int64)

In [22]:
arr_1d.dtype

dtype('int64')

In [23]:
arr_1d = np.array([11,12,13,14,15],dtype='S')
arr_1d

array([b'11', b'12', b'13', b'14', b'15'], dtype='|S2')

In [24]:
print(arr_1d)

[b'11' b'12' b'13' b'14' b'15']


In [25]:
arr_1d = np.array([11,'a',13,14,15],dtype='i')
arr_1d

ValueError: invalid literal for int() with base 10: 'a'

In [26]:
arr_1d = np.array(['11','12','13','14','15'],dtype='i')
arr_1d

array([11, 12, 13, 14, 15], dtype=int32)

In [27]:
scores = np.array([78.5, 88.9,90.56, 77.90],dtype='i')
scores

array([78, 88, 90, 77], dtype=int32)

In [28]:
scores = np.array([78.5, 88.9,90.56, 77.90])
scores

array([78.5 , 88.9 , 90.56, 77.9 ])

In [29]:
arr = scores.astype('i')

In [30]:
arr

array([78, 88, 90, 77], dtype=int32)

In [31]:
scores

array([78.5 , 88.9 , 90.56, 77.9 ])

In [33]:
arr = np.array([1,2,3,4,0,1,1,0,0,4])
arr

array([1, 2, 3, 4, 0, 1, 1, 0, 0, 4])

In [35]:
bool_arr = arr.astype(bool)

In [36]:
bool_arr

array([ True,  True,  True,  True, False,  True,  True, False, False,
        True])

In [38]:
#Numpy Array copy vs view
arr = np.array([1,2,3,4,5,6])
arr_copy = arr.copy() #the copy is a new array 

In [39]:
arr

array([1, 2, 3, 4, 5, 6])

In [40]:
arr_copy

array([1, 2, 3, 4, 5, 6])

In [41]:
arr[-1] = 100
arr

array([  1,   2,   3,   4,   5, 100])

In [42]:
arr_copy

array([1, 2, 3, 4, 5, 6])

In [43]:
arr_copy[0] = 55
arr_copy

array([55,  2,  3,  4,  5,  6])

In [44]:
arr

array([  1,   2,   3,   4,   5, 100])

In [46]:
#view
arr = np.array([1,2,3,4,5,6])
arr_view = arr.view() # the view is just a view of the originl array

In [47]:
arr[4] = -55
print(arr)
print(arr_view)

[  1   2   3   4 -55   6]
[  1   2   3   4 -55   6]


In [49]:
arr_view[1] = 100
print(arr)
print(arr_view)

[  1 100   3   4 -55   6]
[  1 100   3   4 -55   6]


In [50]:
print(arr_copy.base)

None


In [51]:
print(arr_view.base)

[  1 100   3   4 -55   6]


In [52]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

lst = [lst1, lst2]
lst

[[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]]

In [53]:
arr = np.array(lst)

In [54]:
arr.ndim

2

In [55]:
arr.shape

(2, 5)

In [56]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr.ndim

1

In [58]:
arr.shape

(10,)

In [60]:
arr = np.array([1,2,3,4,5,6,7,8,9,10], ndmin=4) 
arr

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]]])

In [61]:
arr.ndim

4

In [62]:
arr.shape

(1, 1, 1, 10)

In [63]:
arr = np.array([ [2,3,4,5], [6,7,8,9] ])
arr

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [64]:
arr.ndim

2

In [65]:
arr.shape

(2, 4)

In [66]:
np.shape(arr)

(2, 4)

In [67]:
arr.shape[0]

2

In [68]:
arr.shape[1]

4

In [69]:
# Reading data from files
fl = open("data.txt", 'r')
print(fl.read())

1, 2, 3
4, 5, 6


In [72]:
f = open("data1.txt", 'w')
f.write("10, 11, 12\n")
f.write("20, 21, 22\n")
f.write("30, 31, 32\n")
f.close()

In [73]:
fl.close()

In [74]:
f = open("data1.txt", 'r')
print(f.read())

10, 11, 12
20, 21, 22
30, 31, 32



In [75]:
arr = np.genfromtxt('data.txt', dtype=None, delimiter = ',')
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
arr.dtype

dtype('int32')

In [77]:
arr = np.genfromtxt('data1.txt', dtype=None)
arr

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]])

In [79]:
arr = np.loadtxt('data1.txt', dtype='<U6')
arr

array([['10', '11', '12'],
       ['20', '21', '22'],
       ['30', '31', '32'],
       ['40', '41', '42']], dtype='<U6')

In [80]:
arr = np.loadtxt('data1.txt', dtype='i8')
arr

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42]], dtype=int64)

In [81]:
f = open("mydata.txt", 'w')
f.write("'c', 'a', 'b'\n")
f.write("20, 21, 22\n")
f.write("True, False, False\n")
f.close()

In [83]:
arr = np.genfromtxt('mydata.txt', dtype='O', delimiter=',')
arr

array([[b"'c'", b" 'a'", b" 'b'"],
       [b'20', b' 21', b' 22'],
       [b'True', b' False', b' False']], dtype=object)