# Parker McQuade
# Week 13 - April 11th, 2023 - April 13th, 2023
# Python - Pandas Series and DataFrame

In [31]:
import numpy as np
from pandas import Series,DataFrame
import pandas as pd

In [2]:
mydataset = { 'Cars' : ["GMC", "Toyota", "Ford"], 'Seats' : [8,6,8]
            }
mydataset

{'Cars': ['GMC', 'Toyota', 'Ford'], 'Seats': [8, 6, 8]}

In [3]:
df = DataFrame(mydataset)
df

Cars  Seats
0     GMC      8
1  Toyota      6
2    Ford      8

In [4]:
print(pd.__version__)

1.0.5


In [5]:
#Panda Series
s = Series([2,5,7,-9,10,1])
s

0     2
1     5
2     7
3    -9
4    10
5     1
dtype: int64

In [6]:
s.values

array([ 2,  5,  7, -9, 10,  1], dtype=int64)

In [7]:
s[1]

5

In [8]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [9]:
# Creating Labels 
s = pd.Series([10,5,30,40], index = ['x','y','w','z'])
s

x    10
y     5
w    30
z    40
dtype: int64

In [10]:
s['x']

10

In [11]:
s['x'] = 20

In [12]:
s

x    20
y     5
w    30
z    40
dtype: int64

In [13]:
# Creating series from numpy array
data = np.array(['a','b','c','d'])
s = Series(data, index = [100,101,102,103])
s

100    a
101    b
102    c
103    d
dtype: object

In [14]:
s[100]

'a'

In [15]:
summer_olypmics = Series([2520,1122,937, 847,713],
                        index =['USA','Russia','Germany','UK','France'])
summer_olypmics

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [16]:
summer_olypmics['USA']

2520

In [17]:
summer_olypmics[summer_olypmics > 800]

USA        2520
Russia     1122
Germany     937
UK          847
dtype: int64

In [18]:
'UK' in summer_olypmics

True

In [19]:
'Itly' in summer_olypmics

False

In [20]:
#Convert Series to dictionary
d = summer_olypmics.to_dict()
d

{'USA': 2520, 'Russia': 1122, 'Germany': 937, 'UK': 847, 'France': 713}

In [21]:
#Convert dictionary to Series
summer_olypmics_new = Series(d)
summer_olypmics_new

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [22]:
#redefine a Series
lst = ['Russia', 'France', 'Spain','Germany','USA','UK','Italy']

s = Series(d, index=lst)
s

Russia     1122.0
France      713.0
Spain         NaN
Germany     937.0
USA        2520.0
UK          847.0
Italy         NaN
dtype: float64

In [23]:
pd.isnull(s)

Russia     False
France     False
Spain       True
Germany    False
USA        False
UK         False
Italy       True
dtype: bool

In [24]:
pd.notnull(s)

Russia      True
France      True
Spain      False
Germany     True
USA         True
UK          True
Italy      False
dtype: bool

In [25]:
s + summer_olypmics

France     1426.0
Germany    1874.0
Italy         NaN
Russia     2244.0
Spain         NaN
UK         1694.0
USA        5040.0
dtype: float64

In [26]:
summer_olypmics

USA        2520
Russia     1122
Germany     937
UK          847
France      713
dtype: int64

In [27]:
summer_olypmics.name =  "Summer Olympic"

In [28]:
summer_olypmics

USA        2520
Russia     1122
Germany     937
UK          847
France      713
Name: Summer Olympic, dtype: int64

In [29]:
summer_olypmics.index.name='Countries'

In [30]:
summer_olypmics

Countries
USA        2520
Russia     1122
Germany     937
UK          847
France      713
Name: Summer Olympic, dtype: int64

In [32]:
# Dataframe
#A 2 dimensoinal dat structure, Like a 2 dimensional array 
#or  table with rows and columns.

data = { 'Calories' : [420, 380, 390],
       'Fruits': ['Orange', 'Banana', 'Grape']
       }
 #Load data into dataframe object
df = pd.DataFrame(data)
df

Calories  Fruits
0       420  Orange
1       380  Banana
2       390   Grape

In [33]:
print(df)

   Calories  Fruits
0       420  Orange
1       380  Banana
2       390   Grape


In [34]:
type(df)

pandas.core.frame.DataFrame

In [35]:
df.describe

<bound method NDFrame.describe of    Calories  Fruits
0       420  Orange
1       380  Banana
2       390   Grape>

In [36]:
df.info

<bound method DataFrame.info of    Calories  Fruits
0       420  Orange
1       380  Banana
2       390   Grape>

In [37]:
df

Calories  Fruits
0       420  Orange
1       380  Banana
2       390   Grape

In [38]:
df.loc[0]

Calories       420
Fruits      Orange
Name: 0, dtype: object

In [39]:
type(df.loc[0])

pandas.core.series.Series

In [40]:
df.values

array([[420, 'Orange'],
       [380, 'Banana'],
       [390, 'Grape']], dtype=object)

In [41]:
df.loc[1]

Calories       380
Fruits      Banana
Name: 1, dtype: object

In [42]:
df.loc[[0,2]]

Calories  Fruits
0       420  Orange
2       390   Grape

In [43]:
type(df.loc[[0,2]])

pandas.core.frame.DataFrame

In [44]:
df['Calories']

0    420
1    380
2    390
Name: Calories, dtype: int64

In [46]:
df['Fruits']

0    Orange
1    Banana
2     Grape
Name: Fruits, dtype: object

In [47]:
type(df['Calories'])

pandas.core.series.Series

In [52]:
data = {'state': ['Ohio', 'Ohio','Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000,2001,2002,2001,2002,2003],
        'pop': [1.5,1.7,3.6,2.4,2.9,3.2]
    
}
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [53]:
df = DataFrame(data)

In [54]:
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [55]:
df.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [56]:
df.tail(2)

state  year  pop
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [59]:
#CHANGING COLUMN ORDERS
DataFrame(data, columns=['year','state','pop'])


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [82]:
#add another column
df2 = DataFrame(data, columns=['year','state','pop','debt'],
              index=['one','two','three','four','five','six']
               )
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [83]:
df2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [84]:
df2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [85]:
df2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [86]:
df2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [87]:
df['year']

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [88]:
df2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [89]:
df2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [90]:
df2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object

In [91]:
df2['debt']=10.5

In [92]:
df2

year   state  pop  debt
one    2000    Ohio  1.5  10.5
two    2001    Ohio  1.7  10.5
three  2002    Ohio  3.6  10.5
four   2001  Nevada  2.4  10.5
five   2002  Nevada  2.9  10.5
six    2003  Nevada  3.2  10.5

In [93]:
df2['debt'] = np.arange(6.0)

In [94]:
df2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [95]:
df2['debt'] = np.random.randn(6)
df2

year   state  pop      debt
one    2000    Ohio  1.5 -0.880807
two    2001    Ohio  1.7 -1.366251
three  2002    Ohio  3.6 -0.709698
four   2001  Nevada  2.4  0.974685
five   2002  Nevada  2.9 -1.599715
six    2003  Nevada  3.2 -0.452735

In [96]:
s = Series([-1.2,-1.5,-1.7], index = ['two','four','five'])
s


two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [97]:
df2['debt'] = s
df2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [98]:
df2['eastern'] =  df2['state'] == 'Ohio'
df2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [99]:
df2.columns

Index(['year', 'state', 'pop', 'debt', 'eastern'], dtype='object')

In [100]:
df2['eastern']

one       True
two       True
three     True
four     False
five     False
six      False
Name: eastern, dtype: bool

In [101]:
df2['debt']

one      NaN
two     -1.2
three    NaN
four    -1.5
five    -1.7
six      NaN
Name: debt, dtype: float64

In [104]:
#Create DataFrame from nested dictionary
data1 = {'Nevada': {2001: 2.4, 2002: 2.9},
        'Ohio': {2000: 1.5, 2001: 1.7,2002: 3.6}
        }
data1

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [105]:
df3 = DataFrame(data1)

In [106]:
df3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [107]:
df3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [109]:
# one index is missing 
df4 = DataFrame(df3,index=[2001,2002,2003])
df4

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [110]:
df3['Ohio']

2001    1.7
2002    3.6
2000    1.5
Name: Ohio, dtype: float64

In [111]:
df3['Ohio'][:1]

2001    1.7
Name: Ohio, dtype: float64

In [112]:
df3['Ohio'][:2]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [113]:
df3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [114]:
df3.index.name='year'

In [115]:
df3

Nevada  Ohio
year              
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [116]:
df3.columns.name='state'

In [117]:
df3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [118]:
df3.loc[2001]

state
Nevada    2.4
Ohio      1.7
Name: 2001, dtype: float64

In [119]:
print(df3.loc[2001])

state
Nevada    2.4
Ohio      1.7
Name: 2001, dtype: float64


In [121]:
df = DataFrame(np.arange(16).reshape(4,4),
                 index=['Ohio', 'Colorado','Utah','New York'],
                 columns=['one','two','three','four']
                )
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [123]:
df.drop(['Colorado'])

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [124]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
df.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [126]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [128]:
df.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [130]:
df.drop(['two','four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [131]:
df.drop(['two','four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [132]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
df1 = df
df.drop('three',inplace=True, axis=1)


In [135]:
df

one  two  four
Ohio        0    1     3
Colorado    4    5     7
Utah        8    9    11
New York   12   13    15

In [136]:
df1

one  two  four
Ohio        0    1     3
Colorado    4    5     7
Utah        8    9    11
New York   12   13    15

In [137]:
df = DataFrame(np.arange(16).reshape(4,4),
                 index=['Ohio', 'Colorado','Utah','New York'],
                 columns=['one','two','three','four']
                )
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [138]:
df['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [139]:
df[['one','four']]

one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

In [140]:
df[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [141]:
df.loc['Utah']

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [142]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
df[df['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [144]:
df > 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [145]:
df[df < 5] = 0 
df

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
df.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [147]:
df.loc['Colorado', 'two']

5

In [149]:
df.loc['Colorado', ['two', 'four']]

two     5
four    7
Name: Colorado, dtype: int32