# Parker McQuade
# Week 12 - April 6th, 2023 - April 11th, 2023
# Python Numpy Universal Functions

In [21]:
import numpy as np

In [2]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [4]:
#randa
arr = np.random.randn(10)
arr

array([ 0.15303211,  0.31086604,  0.07052859,  0.35722116,  0.34712471,
       -2.04832718, -0.77187913,  0.42808515,  0.23248293, -0.56898572])

In [5]:
arr1 = np.random.randn(10) 
arr1

array([ 0.09259961, -0.09541585,  1.77295536, -1.01386172, -1.92757475,
       -1.00395312,  1.53137118, -1.9062159 ,  0.33736218,  0.36974426])

In [6]:
np.add(arr,arr1)

array([ 0.24563172,  0.21545019,  1.84348395, -0.65664055, -1.58045003,
       -3.0522803 ,  0.75949204, -1.47813075,  0.56984511, -0.19924147])

In [7]:
np.maximum(arr,arr1)

array([ 0.15303211,  0.31086604,  1.77295536,  0.35722116,  0.34712471,
       -1.00395312,  1.53137118,  0.42808515,  0.33736218,  0.36974426])

In [8]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr2 = np.arange(9).reshape((3,3))
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.add(arr1, arr2)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [11]:
# Array filtering
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
print(arr>3)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [13]:
np.where(arr<4,0,-1)

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [14]:
np.where(arr <= 3, 0 , -1)

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [15]:
np.where((arr <= 4) & (arr > 2), 0 , -1)

array([[-1, -1, -1],
       [ 0,  0, -1],
       [-1, -1, -1]])

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_b = np.array([True, False, True, True, False])
print(arr1) 
print(arr2) 
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [17]:
list(zip(arr1,arr2,arr_b))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]

In [18]:
arr3 = np.array([v1 if b else v2 for v1, v2, b in zip(arr1,arr2,arr_b)])
arr3

array([ 1, 20,  3,  4, 50])

In [19]:
arr3 = np.where(arr_b, arr1, arr2) 
arr3

array([ 1, 20,  3,  4, 50])

In [22]:
# using where with 2-D
arr1 = np.array ([[1,2], [3,4]]) 
arr2 = np.array ([ [5,6],[7,8]])
cond = np.array ([ [True, False], [True, True]]) 
print(arr1, end= '\n\n') 
print(arr2, end='\n\n') 
print(cond, end= '\n\n')


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ True False]
 [ True  True]]



In [23]:
np.where(cond, arr1, arr2)

array([[1, 6],
       [3, 4]])

In [24]:
from numpy.random import randn
arr = randn(3,3) 
arr

array([[ 1.12379754,  0.3653762 , -0.42957024],
       [-0.53875706,  0.90347445, -0.91533569],
       [ 0.60640377,  0.26370609,  0.91195369]])

In [25]:
np.where(arr<0,0,arr) 

array([[1.12379754, 0.3653762 , 0.        ],
       [0.        , 0.90347445, 0.        ],
       [0.60640377, 0.26370609, 0.91195369]])

In [26]:
arr = np.array([True, False, True, True, False, True])
arr.any()

True

In [27]:
arr.all()

False

In [29]:
# Unique()
fruits = np.array(['Apple', 'Cherry', 'Apple', 'Orange', 'Cherry', 'Banana'])
np.unique(fruits) 

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [30]:
# Descriptive Statistical Measures
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.sum()

45

In [32]:
arr.sum(0)

array([12, 15, 18])

In [33]:
arr.sum(1)

array([ 6, 15, 24])

In [35]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [36]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [38]:
arr.mean()

5.0

In [39]:
arr.mean(0)

array([4., 5., 6.])

In [40]:
arr.mean(1)

array([2., 5., 8.])

In [41]:
np.mean(arr, axis= 0)

array([4., 5., 6.])

In [42]:
np.mean(arr, axis =1)

array([2., 5., 8.])

In [43]:
arr.var()

6.666666666666667

In [44]:
arr.std()

2.581988897471611

In [45]:
arr = np.array([2,3,5,6,7,8,10,2,12])
arr.sort()
arr

array([ 2,  2,  3,  5,  6,  7,  8, 10, 12])

In [46]:
# Joining NumPy Arrays 
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1)
print(arr2)


[1 2 3]
[4 5 6]


In [47]:
arr = np.concatenate((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [48]:
# Joining 2-D arrays
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(5,9).reshape(2,2)
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [50]:
arr = np.concatenate((arr1,arr2), axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [51]:
arr = np.concatenate((arr1,arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [52]:
# Splitting NumPy Arrays
arr = np.array([1,2,3,4,5,6])

split_arr = np.array_split(arr,3)
split_arr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [53]:
type(split_arr)

list

In [54]:
split_arr[0]

array([1, 2])

In [55]:
split_arr = np.array_split(arr,4)
split_arr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [56]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True