# Parker McQuade
# Week 12 - April 6th, 2023
# Python Numpy Universal Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [5]:
#randa
arr = np.random.randn(10)
arr

array([-0.18382436,  2.13955753, -0.21694503, -1.7350082 ,  1.35250671,
       -1.21417127,  0.87289125,  1.50651428, -0.05341321, -1.30109067])

In [7]:
arr1 = np.random.randn(10) 
arr1

array([-1.18202586,  1.37003823,  0.90737032, -0.35284303, -0.8054297 ,
       -0.01327431,  1.15160911,  0.19690273, -1.03737288,  0.31802528])

In [8]:
np.add(arr,arr1)

array([-1.36585022,  3.50959576,  0.6904253 , -2.08785123,  0.54707701,
       -1.22744558,  2.02450036,  1.70341701, -1.09078609, -0.98306539])

In [9]:
np.maximum(arr,arr1)

array([-0.18382436,  2.13955753,  0.90737032, -0.35284303,  1.35250671,
       -0.01327431,  1.15160911,  1.50651428, -0.05341321,  0.31802528])

In [12]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr2 = np.arange(9).reshape((3,3))
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.add(arr1, arr2)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [15]:
# Array filtering
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
print(arr>3)

[[False False False]
 [False  True  True]
 [ True  True  True]]


In [17]:
np.where(arr<4,0,-1)

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [18]:
np.where(arr <= 3, 0 , -1)

array([[ 0,  0,  0],
       [ 0, -1, -1],
       [-1, -1, -1]])

In [19]:
np.where((arr <= 4) & (arr > 2), 0 , -1)

array([[-1, -1, -1],
       [ 0,  0, -1],
       [-1, -1, -1]])

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = arr1*10
arr_b = np.array([True, False, True, True, False])
print(arr1) 
print(arr2) 
print(arr_b)

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]


In [21]:
list(zip(arr1,arr2,arr_b))

[(1, 10, True), (2, 20, False), (3, 30, True), (4, 40, True), (5, 50, False)]

In [22]:
arr3 = np.array([v1 if b else v2 for v1, v2, b in zip(arr1,arr2,arr_b)])
arr3

array([ 1, 20,  3,  4, 50])

In [23]:
arr3 = np.where(arr_b, arr1, arr2) 
arr3

array([ 1, 20,  3,  4, 50])